version: '3'

volumes:
  postgres_dbdata:

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file: postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_dbdata:/var/lib/postgresql/data
    networks:
      - postgres_pgAdmin
  
  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "8082:8080"
    networks:
      - postgres_pgAdmin

networks:
  postgres_pgAdmin:
    driver: bridge
